### ISSUE TITLE
Config Template Example

### ISSUE THREAD

**Issue by donniemoss** [whatUwant/homebridge-sp108e-platform#1]
**Describe Your Problem:**

Have module installed in HomeBridge but do not see how to add SP108E Controllers.   Any help would be appreciated.

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by whatUwant** [comment]
New devices can be added in homebridge UI.
Otherwise make necessary changes to this template before inserting it to homebridge config:
```json
        {
            "devices": [
                {
                    "host": "192.168.1.106",
                    "port": 8189,
                    "name": "Corridor Light",
                    "chip": "SK6812_RGBW",
                    "colorOrder": "GRB",
                    "segments": 2,
                    "ledsPerSegment": 216,
                    "debug": false
                }
            ],
            "name": "SP108EPlatform",
            "platform": "SP108EPlatform"
        }
```
(`"platform": "SP108EPlatform"` should remain unchanged)
